### ISSUE TITLE
default config training failed

### ISSUE THREAD

**Issue by ChuanjunLAN** [huqinghao/PalQuant#1]
Thx for your work, i tried to reimplement your repo by default config you mentioned :
"python main.py --data your-imagenet-data-path --visible_gpus '0,1,2,3' --workers 20 --arch 'resnet18_quant' --epochs 90 --groups 2 --weight_levels 4 --lr_m 0.1 --lr_q 0.0001 -b 256  --act_levels 4 --log_dir "../results/resnet-18/W2A2G2/"
but i cant get a even close result as you put in your paper that quantization level is 2 bits for Resnet18 imagenet dataset, i think your config above is for 4 bits. so is there some setup i missed? wait for your help, thx again

**Comment by huqinghao** [comment]
After refactoring the codes, I only evaluate the model but haven't re-train the model. I will check the codes and args.
BTW, could you post the printed args or the log.txt in the log-dir?

**Comment by huqinghao** [comment]
I have made some updates, and the training logs and models are also uploaded.  Now you can re-run the code with the default config.

**Comment by ChuanjunLAN** [comment]
> I have made some updates, and the training logs and models are also uploaded. Now you can re-run the code with the default config.

Thx for you reply, it works well for the default config. Have a good day
