### ISSUE TITLE
How to evaluate the efficacy of your models on CNN accelerator?

### ISSUE THREAD

**Issue by lixcli** [huqinghao/PalQuant#2]
Hi, 
I wonder is there open-source code of BPVeC? Or you guys reproductive this accelerator then evaluate the efficacy? 
Thanks your share!

**Comment by huqinghao** [comment]
The BPVeC accelerator is optimized based on the BitFusion for 2bit vectorized computation. For performance modeling, we modified the open-source BitFusion simulator to support BPVeC. The BitFusion simulator is at [https://github.com/hsharma35/bitfusion](https://github.com/hsharma35/bitfusion).

**Comment by lixcli** [comment]
thanks:)
